apiVersion: v1
kind: Service
metadata:
  name: frontend-microservices
spec:
  selector:
    app: frontend-microservices
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort
